version: 0.2
phases:
  pre_build:
    commands:
      # Check Image URI is not the default pipeline value
      - |
        if [[ "${IMAGE_URI}" = "MUST_BE_SET" ]]; then
          echo "The IMAGE_URI has not been set by the caller. The value of IMAGE_URI is \"${IMAGE_URI}\""
          exit 1
        fi

      # Get task definition with tags
      - echo "Existing mailchimp-sync task definition name is ${TASK_DEFINITION_NAME}"
      - ECS_TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "${TASK_DEFINITION_NAME}" --include TAGS)

      # Extract tags to preserve them
      - |
        TAGS=$(echo "${ECS_TASK_DEFINITION}" | jq -c '.tags // []')
        echo "Preserving tags: ${TAGS}"

      # Delete any reference to the old image from the task definition and add the new image uri
      - |
        NEW_ECS_TASK_DEFINITION=$(echo "${ECS_TASK_DEFINITION}" | jq --arg "INPUT_IMAGE_URI" "${IMAGE_URI}" '.taskDefinition | .containerDefinitions[0].image = $INPUT_IMAGE_URI | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) |  del(.registeredAt)  | del(.registeredBy)')
        echo "Replaced image uri with ${IMAGE_URI}"

  build:
    commands:
      # Register a new task definition with tags
      - |
        NEW_ECS_TASK_DEFINITION_ARN=$(aws ecs register-task-definition --cli-input-json "$NEW_ECS_TASK_DEFINITION" --tags "$TAGS" | jq -r '.taskDefinition.taskDefinitionArn' )
        echo "New mailchimp-sync task definition ARN: ${NEW_ECS_TASK_DEFINITION_ARN}"
