# yaml-language-server: $schema=../spec/deployments/running_order_schema.json
##
# This file serves two purposes
#
# 1. To document what order our Terraform needs to be run in to create a new
#    environment, or otherwise to successfully apply it to an existing one
#
# 2. To be parsed and turned into a running order in a pipeline. Driving
#    pipeline structure from this document means this document must always
#    be up-to-date and correct.
#
# N.B. It does not cover how to run the Terraform for the deploy account.
#
# The running order is made up of layers and phases.
#
# A layer is a logical grouping of Terraform roots that combine to fulfil some
# responsibility, such as configuring an AWS account with IAM roles, password
# policies etc.
#
# A layer is broken up into one or more phases. A phase contains a set of
# Terraform roots which can be run in parallel because they aren't
# interdependent.
#
# Additional phases are used when one or more Terraform roots have a dependency
# on a resource or value from another Terraform root in the same layer.
#
# Terraform root names are relative to the `infra/deployments` directory (the
# same as elsewhere in this repository(
##
---
running-order:
  deploy:
    layers:
      - name: Deploy Account
        manual: true
        phases:
          - roots:
              - deploy/account
              - deploy/engineer-access
              - deploy/coordination
              - deploy/ecr
              - deploy/e2e-tests-image-builder
              - deploy/image-builders
          - roots:
              - deploy/tools
  forms:
    layers:
      - name: Account
        manual: true
        phases:
          - roots:
              - forms/account

      - name: GOV.UKForms
        manual: false
        phases:
          - roots:
              - forms/environment
              - forms/ses
          - roots:
              - forms/auth0
          - roots:
              - forms/redis
              - forms/rds
          - roots:
              - forms/forms-product-page
              - forms/forms-admin
              - forms/forms-runner
          - roots:
              - forms/health
          - roots:
              - forms/pipelines
              - forms/dns
  integration:
    layers:
      - name: Integration Account
        manual: true
        phases:
          - roots:
              - integration/account
              - integration/review
