#!/usr/bin/env ruby

# frozen_string_literal: true

# This script updates the Ruby and Docker Alpine Versions for each app in the
# necessary places to make updating simpler.
#
# Change the NEW_RUBY_VERSION and or the DOCKER_ALPINE_VERSION to the desired
# new version and then run the script. It will create a branch, make the
# necessary updates, commit the changes and push to Github for you to raise a
# PR.

def system!(*args, **options)
  system(*args, **options, exception: true)
end

# Check that Docker is running
unless system("docker info", [:out, :err] => "/dev/null")
  abort "Docker is not running. Docker is required to find the correct docker
  base image for the new version of Ruby. Start Docker and try again. more
  info here: https://www.docker.com/products/docker-desktop/"
end

# Update these values as necessary and then run the script
NEW_RUBY_VERSION = "3.2.2"
DOCKER_ALPINE_VERSION = "3.18"

# Constants that should not need to be updated
GIT_BRANCH_NAME = "bump_ruby_to_#{NEW_RUBY_VERSION}"
APPS = %w[forms-api forms-admin forms-runner forms-product-page forms-e2e-tests]

# Checks out main branch and pulls latests. Then creates a new
# branch for the updates. If the branch already exists it continues
# on and uses it.
def setup_git_branch
  system! "git checkout main"
  system! "git pull"
  system %(git branch "#{GIT_BRANCH_NAME}") || puts("Continuing with existing branch")
  system! %(git checkout "#{GIT_BRANCH_NAME}")
end

# Find the manifest list sha for the version of ruby and alpine
def get_new_docker_base_image_sha
  `docker buildx imagetools inspect ruby:#{NEW_RUBY_VERSION}-alpine#{DOCKER_ALPINE_VERSION}`
    .each_line.grep(/Digest/).first
    .split(":", 2)[1]
    .strip
end

# Main script begins here
puts "Updating to #{NEW_RUBY_VERSION}"
MANIFEST_LIST_SHA = get_new_docker_base_image_sha
APPS.each do |app|
  puts "\n\n****** BEGINNING UPDATE OF #{app} ********"
  oldpwd = Dir.pwd; Dir.chdir "../../#{app}"

  setup_git_branch

  puts "Updating .ruby-version file"
  File.write ".ruby-version", "#{NEW_RUBY_VERSION}\n"

  puts "Updating Gemfile"
  system! %(sed -i '' 's/^ruby.*$/ruby "#{NEW_RUBY_VERSION}"/' Gemfile)

  puts "Running 'bundle install' to update Gemfile.lock"
  system! "bundle install", :out => "/dev/null"

  puts "Updating version in Dockerfile"
  system! %(sed -i '' 's/^FROM ruby:.* AS/FROM ruby:#{NEW_RUBY_VERSION}-alpine#{DOCKER_ALPINE_VERSION}@#{MANIFEST_LIST_SHA} AS/' Dockerfile)

  puts "Committing changes"
  system! "git add .ruby-version"
  system! "git add Dockerfile"
  system! "git add Gemfile"
  system! "git add Gemfile.lock"
  system(%(git commit -S -m "Bump Ruby to #{NEW_RUBY_VERSION}")) \
    && system(%(git push -u origin "#{GIT_BRANCH_NAME}")) \
    || puts("There are no commits, perhaps you've already run this script?")
  puts "****** FINISHED UPDATING #{app} ********\n\n"

  Dir.chdir oldpwd
end

puts "Now raise a PR for each repo for the branches named #{GIT_BRANCH_NAME}"
