apiVersion: 1

datasources:
  - name: Mimir
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus
    url: ${MIMIR_URL}/prometheus
    isDefault: false
    version: 1
    editable: false

  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    uid: tempo
    url: http://localhost:3200
    isDefault: true
    version: 1
    editable: false
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus

  - name: CloudWatch
    type: cloudwatch
    access: proxy
    orgId: 1
    uid: cloudwatch
    isDefault: false
    version: 1
    editable: false
    jsonData:
      authType: default
      defaultRegion: eu-west-2

  - name: GitHub
    type: grafana-github-datasource
    access: proxy
    orgId: 1
    uid: github
    isDefault: false
    version: 1
    editable: false
    jsonData:
      selectedAuthType: personal-access-token
    secureJsonData:
      accessToken: ${GITHUB_DATASOURCE_PAT}
