apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://localhost:3200
    isDefault: true
    version: 1
    editable: false
    jsonData:
      httpMethod: GET
