# frozen_string_literal: true

source "https://rubygems.org"

gem "aws-sdk-codepipeline", "~> 1.90"
gem "aws-sdk-sns", "~> 1.91"

group :development, :test do
  gem "rspec", "~> 3.13"
  gem "rubocop-govuk", "~> 5.0"
end
