# frozen_string_literal: true

source "https://rubygems.org"

gem "aws-sdk-codepipeline", "~> 1.75"
gem "aws-sdk-sns", "~> 1.77"

group :development, :test do
  gem "rspec", "~> 3.13"
  gem "rubocop-govuk", "~> 4.18"
end
