version: 0.2

phases:
  install:
    commands:
      - set -e
      - export TERRAFORM_VERSION=$(< .review_apps/.terraform-version)
      - curl --fail --location --silent --show-error "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_arm64.zip" -o "terraform_${TERRAFORM_VERSION}_linux_arm64.zip"
      - export SHA256_SUM=$(curl --fail --location --silent --show-error "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS" | grep "terraform_${TERRAFORM_VERSION}_linux_arm64.zip$")
      - echo "${SHA256_SUM}" | sha256sum --check --status -
      - unzip "terraform_${TERRAFORM_VERSION}_linux_arm64.zip"
      - mv terraform /usr/local/bin/terraform
    finally:
      - terraform --version

  pre_build:
    commands:
      - cd .review_apps
      - terraform init -backend-config="key=review-apps/${APPLICATION_NAME}/pr-${PR_NUMBER}.tfstate"

  build:
    commands:
      - |
        terraform destroy \
          -var "pull_request_number=${PR_NUMBER}" \
          -var "${APPLICATION_NAME//-/_}_container_image=placeholder" \
          -no-color \
          -auto-approve
