# frozen_string_literal: true

source "https://rubygems.org"

gem "aws-sdk", "~> 3"
gem "colorize"
gem "notifications-ruby-client"
gem "rexml", "~> 3.3" # aws-sdk-secretsmanager an xml library
gem "rspec"
gem "rubocop-govuk", "~> 5.0"

group :development do
  gem "debug"
end
