# frozen_string_literal: true

source "https://rubygems.org"

gem "aws-sdk", "~> 3"
gem "colorize"
gem "notifications-ruby-client"
gem "rspec"
gem "rubocop-govuk", "~> 4.18"

group :development do
  gem "debug"
end
