version: 0.2
artifacts:
  enable-symlinks: yes
phases:
  install:
    commands:
      # install terraform
      - set -e
      - uname -a
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install "terraform-${TERRAFORM_VERSION}"
    finally:
      - terraform --version
  build:
    commands:
      - echo "Assuming role ${DEPLOYER_ROLE_ARN}"
      - aws sts get-caller-identity
      - sts="$(aws sts assume-role --role-arn "$DEPLOYER_ROLE_ARN" --role-session-name "deployer" --external-id "$EXTERNAL_ID")"
      - export AWS_ACCESS_KEY_ID="$(echo "$sts" | jq '.Credentials.AccessKeyId' -r )"
      - export AWS_SECRET_ACCESS_KEY="$(echo "$sts" | jq '.Credentials.SecretAccessKey' -r )"
      - export AWS_SESSION_TOKEN="$(echo "$sts" | jq '.Credentials.SessionToken' -r )"
      - aws sts get-caller-identity
      - cd "${DEPLOY_DIRECTORY}"
      - terraform init
      - terraform apply --auto-approve --var image_tag="${IMAGE_TAG}"
  post_build:
    commands:
      - '[ ${CODEBUILD_BUILD_SUCCEEDING:-0} -eq 1 ] || exit 1'
      - echo "Waiting for ECS to finish updating"
      - cd "${CODEBUILD_SRC_DIR}/infra/modules/code-build-deploy-ecs/scripts"
      - pwd
      - ./wait-for-deploy.sh "${SERVICE_NAME}" "${CLUSTER_NAME}"
