---
metadata:
    name: "Check that autoscaling target minimum values are greater than zero"
    id: "CKV2_FORMS_AWS_5"
    category: "CONVENTION"
scope:
    provider: "AWS"
definition:
    and:
        - cond_type: "attribute"
          resource_types:
              - "aws_appautoscaling_target"
          attribute: "min_capacity"
          operator: "greater_than"
          value: 0
    