# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "activesupport", "~> 8.0"
gem "activesupport-duration-human_string", "~> 1.0"
gem "aws-sdk-codepipeline", "~> 1.93"
gem "concurrent-ruby", require: "concurrent"
gem "puma", "~> 6.5"
gem "rackup", "~> 2.2"
gem "rspec", "~> 3.13"
gem "rubocop-govuk", "~> 5.0"
gem "sinatra", "~> 4.1"

group :development, :test do
  gem "libxml-ruby", "~>5.0.3"
end
