# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sinatra", "~> 4.0"

gem "rackup", "~> 2.1"

gem "aws-sdk-codepipeline", "~> 1.69"

gem 'concurrent-ruby', require: 'concurrent'

gem "rspec", "~> 3.13"

gem "activesupport", "~> 7.1"

gem "activesupport-duration-human_string", "~> 1.0"

group :development, :test do
  gem "libxml-ruby", "~>5.0.3"
end