version: 0.2
phases:
  install:
    commands:
      # install terraform
      - uname -a
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install "terraform-${TERRAFORM_VERSION}"
    finally:
      - terraform --version
  build:
    commands:
      - echo "Assuming role ${DEPLOYER_ROLE_ARN}"
      - aws sts get-caller-identity
      - sts="$(aws sts assume-role --role-arn "$DEPLOYER_ROLE_ARN" --role-session-name "deployer")"
      - export AWS_ACCESS_KEY_ID="$(echo "$sts" | jq '.Credentials.AccessKeyId' -r )"
      - export AWS_SECRET_ACCESS_KEY="$(echo "$sts" | jq '.Credentials.SecretAccessKey' -r )"
      - export AWS_SESSION_TOKEN="$(echo "$sts" | jq '.Credentials.SessionToken' -r )"
      - aws sts get-caller-identity
      - cd "${DEPLOY_DIRECTORY}"
      - ls
      - terraform init
      - terraform ${TERRAFORM_COMMAND} --var image_tag="${IMAGE_TAG}"
