version: 0.2
phases:
  install:
    commands:
      - set -e
      - ruby -v
      - cd /app
      - bundle -v
      - bundle install
  build:
    commands:
      - bundle exec rspec spec/features/smoke_tests_spec.rb
